### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by collinanderson**
Thanks to @AcmeProgramming for the idea.

### CODE REVIEW

**Comment by jonthdiaz** [comment]
i'm using this template-email and migrate to python 3.4 i'd like to get access to this pull request, could you help me with that

Thanks...

**Comment by collinanderson** [comment]
git pull https://github.com/collinanderson/django-templated-email python3

**Comment by jonthdiaz** [comment]
thanks you.

**Comment by illing2005** [comment]
Sorry, didn't see that there is already a python3 pull request.
Any chance that this will be pulled in master?

**Pull request closed without merging**
