### PR TITLE
Update to work with Django 1.8

### PR DESCRIPTION
**Pull request by denaje**

### CODE REVIEW

**Comment by BradWhittington** [comment]
Hey, can you wrap the importlib import in a try/catch (i.e. try the django version first, then the python3 importlib), and same for the template context. New releases should still be backwards compatible.

**Comment by denaje** [comment]
Updated

**Comment by PprOR** [comment]
Hello Brad,

Could you please consider updating the pip version for this app according to this change.

Thanks

**Comment by jbinary** [comment]
@PprOR +1, is there any hope to get this into pip?

**Pull request merged**
